bobcat:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  front_right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_right_wheel_joint
    pid: {p: 1000.0, i: 0.00, d: 0.0}
  front_left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_left_wheel_joint
    pid: {p: 1000.0, i: 0.00, d: 0.0}
  back_right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: back_right_wheel_joint
    pid: {p: 1000.0, i: 0.00, d: 0.0}
  back_left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: back_left_wheel_joint
    pid: {p: 1000.0, i: 0.00, d: 0.0}
  back_arm_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_arm_joint
    pid: {p: 700.0, i: 6.00, d: 100.0, i_clamp: 60}
  front_arm_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_arm_joint
    pid: {p: 700.0, i: 6.00, d: 100.0, i_clamp: 60}
  loader_position_controller:
    type: effort_controllers/JointPositionController
    joint: loader_joint
    pid: {p: 700.0, i: 6.00, d: 100.0, i_clamp: 60}
  shaft_position_controller:
    type: effort_controllers/JointPositionController
    joint: shaft_joint
    pid: {p: 700.0, i: 6.00, d: 100.0, i_clamp: 60}
  cylinder_position_controller:
    type: effort_controllers/JointPositionController
    joint: cylinder_joint
    pid: {p: 700.0, i: 6.00, d: 100.0, i_clamp: 60}
